DiyetSpor/DiyetSporWeb/Controllers/UyeController.cs
using DiyetSporWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DiyetSporWeb.Controllers
{
    [AllowAnonymous]
    public class UyeController : Controller
    {
        dbdiyetsporEntities db = new dbdiyetsporEntities();
        // GET: Uye
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UyeDanismanListele()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Blog()
        {
            var blog = db.tblBlog.Where(x => x.blogAktiflik == true).ToList();
            return View(blog);
        }

        [HttpGet]
        public ActionResult Bilgilerim()
        {
            int? id = Convert.ToInt32(HttpContext.User.Identity.Name);
            var kullanici = db.tblKullanici.Find(id);
            return View(kullanici);
        }
        [HttpGet]
        public ActionResult UyeBilgiGetir()
        {
            int? id = Convert.ToInt32(HttpContext.User.Identity.Name);
            var kullanici = db.tblKullanici.Find(id);
            return View(kullanici);
        }
        [HttpPost]
        public ActionResult UyeBilgiGuncelle(tblKullanici k)
        {
            int? id = Convert.ToInt32(HttpContext.User.Identity.Name);
            var kullanici = db.tblKullanici.Find(id);
            kullanici.kullaniciAd = k.kullaniciAd;
            kullanici.kullaniciSoyad = k.kullaniciSoyad;
            kullanici.kullaniciTelefon = k.kullaniciTelefon;
            kullanici.kullaniciEmail = k.kullaniciEmail;
            kullanici.kullaniciSifre = k.kullaniciSifre;
            db.SaveChanges();
            return RedirectToAction("Bilgilerim");
        }


        [HttpGet]
        public ActionResult DanismanTalebindeBulun()
        {
            List<uyeDanismanTalepModel> danismanlar = new List<uyeDanismanTalepModel>();
            //AKTİF OLAN DANIŞMANLARI AL BİLGİLERİNİ ATA VE VİEW E TAŞI
            var kullanicilar = db.tblKullanici.Where(x => x.kullaniciTipi == "D" || x.kullaniciTipi == "S").ToList(); 
            foreach (var k in kullanicilar)
            {
                uyeDanismanTalepModel u = new uyeDanismanTalepModel();
                u.kullaniciAd = k.kullaniciAd;
                u.kullaniciSoyad = k.kullaniciSoyad;
                u.kullaniciid = k.kullaniciid;
                u.kullaniciTipi = k.kullaniciTipi;
                
                danismanlar.Add(u);
            }
            return View(danismanlar);
        }
        [HttpGet]
        public ActionResult UyeDanismanBasvur(int id)
        {
            int uyeid = Convert.ToInt32(HttpContext.User.Identity.Name);
            tblTalep talep = new tblTalep();
            talep.talepEden = uyeid;
            talep.talepEdilenDanisman = id;
            talep.talepDurum = false;
            talep.talepTarihi = Convert.ToDateTime(DateTime.Now);
            var danisman = db.tblKullanici.Find(id);
            if (danisman.kullaniciTipi == "D")
            {
                talep.talepTip = "DİYET";
            }
            else
            {
                talep.talepTip = "ANTREMAN";
            }
            db.tblTalep.Add(talep);
            db.SaveChanges();
            //TALEP OLUŞTURULDU
            return RedirectToAction("Index");
        }




        public ActionResult DenemeMinikKartlar()
        {
            return View();
        }
        public ActionResult DenemeGrafikler()
        {
            return View();
        }
        public ActionResult DenemeButonGeriKalanlar()
        {
            return View();
        }

    }
}

DiyetSpor/DiyetSporWeb/Views/Uye/Bilgilerim.cshtml
@using DiyetSporWeb.Models
@model tblKullanici
@{
    ViewBag.Title = "Bilgilerim";
    Layout = "~/Views/Shared/_UyeLayout.cshtml";
}

<h2>Bilgilerim</h2>
 
<div class="container">

    <form>
        <table border="0">
            <tr>
                <td>
                    <label>Kullanici id: </label>
                </td>
                <td>
                    @Model.kullaniciid

                </td>
            </tr>
            <tr>
                <td>
                    <label>Ad ve soyad : </label>
                </td>
                <td>
                    @Model.kullaniciAd @Model.kullaniciSoyad
                </td>
            </tr>
            <tr>
                <td>
                    <label>TC numarası: </label>
                </td>
                <td>
                    @Model.kullaniciTc
                </td>
            </tr>
            <tr>
                <td>
                    <label>Email: </label>
                </td>
                <td>
                    @Model.kullaniciEmail
                </td>
            </tr>

            <tr>
                <td>
                    <label>Doğum tarihi : </label>
                </td>
                <td>
                    @Model.kullaniciDogumTarihi
                </td>
            </tr>
            <tr>
                <td>
                    <label>Kayıt Tarihi : </label>
                </td>
                <td>
                    @Model.kullaniciKayitTarihi
                </td>
            </tr>
            <tr>
                <td>
                    <label>Telefon numarası : </label>
                </td>
                <td>
                    @Model.kullaniciTelefon
                </td>
            </tr>
            <tr>
                <td>
                    <label>Şifreniz : </label>
                </td>
                <td>
                    @Model.kullaniciSifre
                </td>
            </tr>
        </table>
    </form>
    <a href="/Uye/UyeBilgiGetir" class="btn btn-success">Güncelle</a>

</div>

DiyetSpor/DiyetSporWeb/Views/Uye/Blog.cshtml
@using DiyetSporWeb.Models
@model List<tblBlog>
@{
    ViewBag.Title = "Blog";
    Layout = "~/Views/Shared/_UyeLayout.cshtml";
}

<h2>Blog</h2>

@foreach (var blog in Model)
{

    <!-- Basic Card Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">@blog.blogBaslik  |       Blog  Puan:   @blog.blogPuan </h6>
        </div>
        <div class="card-body">
            @blog.blogDetay
        </div>
    </div>
    <hr />
}

DiyetSpor/DiyetSporWeb/Views/Uye/DanismanTalebindeBulun.cshtml
@using DiyetSporWeb.Models
@model List<uyeDanismanTalepModel>
@{
    ViewBag.Title = "DanismanTalebindeBulun";
    Layout = "~/Views/Shared/_UyeLayout.cshtml";
}
 
<div class="container-fluid">

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Aktif Danışmanlar</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Ad Soyad</th>
                            <th>Danışman Tipi</th>
                            <th>BAŞVUR</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Ad Soyad</th>
                            <th>Danışman Tipi</th>
                            <th>BAŞVUR</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var danisman in Model)
                        {
                            <tr>
                                <td>@danisman.kullaniciAd @danisman.kullaniciSoyad </td>

                                @if (danisman.kullaniciTipi == "D")
                                {
                                    <td>DİYETİSYEN</td>
                                }
                                else
                                {
                                    <td>SPOR ANTRENÖRÜ</td>
                                }
                                <td>
                                    <a href="/Uye/UyeDanismanBasvur/@danisman.kullaniciid" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">BAVŞUR</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

DiyetSpor/DiyetSporWeb/Views/Uye/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_UyeLayout.cshtml";
}

<h2>Anasayfa</h2>

DiyetSpor/DiyetSporWeb/Views/Uye/UyeBilgiGetir.cshtml
@using DiyetSporWeb.Models
@model tblKullanici
@{
    ViewBag.Title = "UyeBilgiGetir";
    Layout = "~/Views/Shared/_UyeLayout.cshtml";
}
<h2>Bilgi GÜncelleme</h2>

@using (Html.BeginForm("UyeBilgiGuncelle", "Uye", FormMethod.Post))
{
    <div class="form-group">
        <div>
            <lable>Kullanici id</lable>
            @Html.TextBoxFor(m => m.kullaniciid, new { @class = "form-control", @readonly = "readonly" })
        </div>
        <div>
            <lable>Ad</lable>
            @Html.TextBoxFor(m => m.kullaniciAd, new { @class = "form-control", required = "", maxlength = "20" })
        </div>
        <div>
            <lable>Soyad</lable>
            @Html.TextBoxFor(m => m.kullaniciSoyad, new { @class = "form-control", required = "", maxlength = "20" })
        </div>
        <div>
            <lable>Kullanici TC numarası</lable>
            @Html.TextBoxFor(m => m.kullaniciTc, new { @class = "form-control", @readonly = "readonly" })
        </div>
        <div>
            <label>Şifresi</label>
            @Html.TextBoxFor(m => m.kullaniciSifre, new { @class = "form-control", required = "", maxlength = "10" })
            @Html.ValidationMessageFor(m => m.kullaniciSifre, "", new { @style = "color:red" })
        </div>
        <div>
            <lable>Müşteri Doğum Günü</lable>
            @Html.TextBoxFor(m => m.kullaniciDogumTarihi, new { @class = "form-control", @readonly = "readonly" })
        </div>
        <div>
            <lable>Müşteri Telefon</lable>
            @Html.TextBoxFor(m => m.kullaniciTelefon, new { @class = "form-control", maxlength = "11" })
            @Html.ValidationMessageFor(m => m.kullaniciTelefon, "", new { @style = "color:red" })
        </div>
        <div>
            <lable>Müşteri Eposta</lable>
            @Html.TextBoxFor(m => m.kullaniciEmail, new { @class = "form-control", maxlength = "100" })
            @Html.ValidationMessageFor(m => m.kullaniciEmail, "", new { @style = "color:red" })
        </div>

    </div>
    <button type="submit" class="form-control success">Güncelle</button>
}

DiyetSpor/DiyetSporWeb/Views/Uye/UyeDanismanListele.cshtml
@{
    ViewBag.Title = "UyeDanismanListele";
    Layout = "~/Views/Shared/_UyeLayout.cshtml";
}

<h2>UyeDanismanListele</h2>