DiyetSpor/DiyetSporWeb/Controllers/SecurityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DiyetSporWeb.Models;

namespace DiyetSporWeb.Controllers
{
    public class SecurityController : Controller
    {
        dbdiyetsporEntities db = new dbdiyetsporEntities();
        // GET: Security
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous] 
        public ActionResult Login(loginModel kullanici)/*Entitden kullanıcı alıp kontrol edicez*/
        {

            var kullaniciInDb = db.tblKullanici.FirstOrDefault(x=>x.kullaniciEmail == kullanici.kullaniciEmail && x.kullaniciSifre==kullanici.kullaniciSifre) ;
            if(kullaniciInDb != null)
            {
                FormsAuthentication.SetAuthCookie(Convert.ToString(kullaniciInDb.kullaniciid),false);
                if (kullaniciInDb.kullaniciTipi == "U")
                {
                    return RedirectToAction("Index", "Uye");
                }
                else if (kullaniciInDb.kullaniciTipi=="A")
                {
                    return RedirectToAction("Index","Admin");
                }
                else if (kullaniciInDb.kullaniciTipi == "D")
                {
                    return RedirectToAction("Index", "DanismanDiyet");
                }
                else if (kullaniciInDb.kullaniciTipi == "S")
                {
                    return RedirectToAction("Index","DanismanSpor");
                }
                else
                {
                    return RedirectToAction("Index","Hata");
                } 
            }
            else
            {
                ViewBag.hatamesaji = "Hatalı Giriş Denemesi";
                return View();
            }
        }
        

        public ActionResult Singout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
        
        [AllowAnonymous]
        [HttpGet]
        public ActionResult SingUp() // KAYIT OL GET
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult SingUp(kullaniciKayitModel yeniuye)
        {
            if (!ModelState.IsValid)
            {
                return View("SingUp");
            }
            var kullanici = new tblKullanici();
            kullanici.kullaniciAd = yeniuye.kullaniciAd;
            kullanici.kullaniciSoyad = yeniuye.kullaniciSoyad;
            kullanici.kullaniciTc = yeniuye.kullaniciTc;
            kullanici.kullaniciCinsiyet = yeniuye.kullaniciCinsiyet;
            kullanici.kullaniciDogumTarihi = Convert.ToDateTime(yeniuye.kullaniciDogumTarihi);
            kullanici.kullaniciEmail = yeniuye.kullaniciEmail;
            kullanici.kullaniciSifre =Convert.ToInt32( yeniuye.kullaniciSifre);
            kullanici.kullaniciTelefon = yeniuye.kullaniciTelefon;
            kullanici.kullaniciTipi = yeniuye.kullaniciTipi;
            kullanici.kullaniciKayitTarihi = Convert.ToDateTime( DateTime.Now);
            kullanici.kullaniciHesapAKtiflik = true;
            if(yeniuye.kullaniciTipi != "U")
            {
                kullanici.kullaniciPuan = 0;
                kullanici.kullaniciDanismanDurum = false;
            }
            db.tblKullanici.Add(kullanici);
            db.SaveChanges();
            if (yeniuye.kullaniciTipi !="U")
            {
                //YENİ TALEP OLUŞTUR
                talep talepnesne = new talep();
                talepnesne.danismantalepolustur(yeniuye.kullaniciTc);           
            }
           
            return RedirectToAction("Index","Home");
        }

        //[AllowAnonymous]
        //[HttpPost]
        //public ActionResult SingUp( int i ,string musteriTip /* müsteri model nesnesi gelecek*/) //KAYIT OL POST
        //{
        //    // müşteri kaydet
        //    return View();
        //}
        [HttpGet]
        [AllowAnonymous]
        public ActionResult ForgotPassword()
        {
            return View();
        }
        [HttpPost]
        [AllowAnonymous]
        public ActionResult ForgotPassword(int id) //GELECEK VERiYE DİKKAT
        {
            return View();
          
        }
    }
}

DiyetSpor/DiyetSporWeb/Views/Security/ForgotPassword.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Forgot Password</title>

    <!-- Custom fonts for this template-->
    <link href="~/Sources/AdminAnasayfa/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Sources/AdminAnasayfa/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Şifrenizi mi Unuttunuz?</h1>
                                        <p class="mb-4">Mail Adresinize yeni şifrenizi gönderelim.</p>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                                        </div>
                                        <a href="login.html" class="btn btn-primary btn-user btn-block">
                                           Şifreyi sıfırla
                                        </a>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="~/Security/Singup">Hesap Oluştur!</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="~/Security/Login">Mevcut Hesabınız mı var? Giriş Yap!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Sources/AdminAnasayfa/vendor/jquery/jquery.min.js"></script>
    <script src="~/Sources/AdminAnasayfa/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Sources/AdminAnasayfa/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Sources/AdminAnasayfa/js/sb-admin-2.min.js"></script>
    <script src="~/Sources/AdminAnasayfa/js/sb-admin-2.min.js"></script>

</body>

</html>

DiyetSpor/DiyetSporWeb/Views/Security/Login.cshtml
@model  DiyetSporWeb.Models.loginModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V20</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="~/Sources/Login/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Sources/Login/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Sources/Login/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Sources/Login/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Sources/Login/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Sources/Login/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Sources/Login/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Sources/Login/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Sources/Login/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Sources/Login/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Sources/Login/css/main.css">
    <!--===============================================================================================-->
</head>
<body>
    <div class="limiter">
        <div class="container-login100">

            <div class="wrap-login100 p-b-160 p-t-50">
               

                @using (Html.BeginForm("Login", "Security", FormMethod.Post, new { @class = "login100-form validate-form" }))
                 {

                    <span class="login100-form-title p-b-43">
                       @ViewBag.hatamesaji
                    </span>

                    <div class="wrap-input100 rs1 validate-input" data-validate="Email is required">
                        <input class="input100" type="text" name="kullaniciEmail">
                        <span class="label-input100">E mail</span>
                    </div>

                    <div class="wrap-input100 rs2 validate-input" data-validate="Password is required">
                        <input class="input100" type="password" name="kullaniciSifre">
                        <span class="label-input100">Sifre</span>
                    </div>

                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn" type="submit">
                            Giris yap
                        </button>
                    </div>

                    <div class="text-center w-full p-t-23">
                        <a href="~/Security/Singup" class="txt1">
                            Üye ol!
                            <p style="font-size:large; font:bold; color:white">  - </p>
                        </a>
                        <a href="~/Security/ForgotPassword" class="txt1">
                            Forgot password?
                        </a>
                    </div>
                 }

            </div>

        </div>
    </div>





    <!--===============================================================================================-->
    <script src="~/Sources/Login/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Sources/Login/vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Sources/Login/vendor/bootstrap/js/popper.js"></script>
    <script src="~/Sources/Login/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Sources/Login/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="~/Sources/Login/vendor/daterangepicker/moment.min.js"></script>
    <script src="~/Sources/Login/vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
    <script src="~/Sources/Login/vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
    <script src="~/Sources/Login/js/main.js"></script>

</body>
</html>

DiyetSpor/DiyetSporWeb/Views/Security/SingUp.cshtml
@model DiyetSporWeb.Models.kullaniciKayitModel
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form by Colorlib</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="~/Sources/KayitEkran/fonts/material-icon/css/material-design-iconic-font.min.css">

    <!-- Main css -->
    <link rel="stylesheet" href="~/Sources/KayitEkran/css/style.css">
</head>
<body>

    <div class="main">
        <div class="container">
            <div class="signup-content">
                <div class="signup-img">
                    <img src="~/Sources/KayitEkran/images/signup-img.jpg" alt="">
                </div>
                <div class="signup-form">
                    <form method="POST" class="register-form" id="register-form">
                        <h2>Kayıt olmak ister misiniz...</h2>
                        <div class="form-row">
                            <div class="form-group">
                                <label>Ad :</label>
                                <input type="text" name="kullaniciAd" id="name" required />
                                 @Html.ValidationMessageFor(m => m.kullaniciAd, "", new { @style = "color:blue" })
                            </div>
                            <div class="form-group">
                                <label>Soyad :</label>
                                <input type="text" name="kullaniciSoyad" id="father_name" required />
                            </div>
                        </div>
                        <div class="form-group">
                            <label>E mail :</label>
                            <input type="email" name="kullaniciEmail" id="address" required />
                        </div>
                        <div class="form-row">
                            <div class="form-group">
                                <label>TC no :</label>
                                <input type="number" name="kullaniciTc" id="name" required />
                            </div>
                            <div class="form-group">
                                <label>Telefon :</label>
                                <input type="number" name="kullaniciTelefon" id="father_name" required />
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Doğum Tarihi : </label>
                            <input type="date" name="kullaniciDogumTarihi" />
                        </div>

                        <div class="form-group">
                            <label>Cinsiyet Seçiniz :</label>
                            <div class="form-select">
                                <select name="kullaniciCinsiyet" id="state">
                                    <option value="true">ERKEK</option>
                                    <option value="false">KADIN</option>
                                </select>
                                <span class="select-icon"><i class="zmdi zmdi-chevron-down"></i></span>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group">
                                <label>Kullanıcı Tipi Seçiniz :</label>
                                <div class="form-select">
                                    <select name="kullaniciTipi" id="state">
                                        <option value="U">ÜYE</option>
                                        <option value="D">DİYETİSYEN</option>
                                        <option value="S">ANTRENÖR</option>
                                    </select>
                                    <span class="select-icon"><i class="zmdi zmdi-chevron-down"></i></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Şifre :</label>
                                <input type="number" name="kullaniciSifre" id="name" required />
                            </div>
                        </div>
                        <div class="form-submit">
                            <input type="submit" value="Hepsini Sil" class="submit" name="reset" id="reset" />
                            <input type="submit" value="Kayıt ol" class="submit" name="submit" id="submit" />
                        </div>
                    </form>

                </div>
            </div>
        </div>

    </div>

    <!-- JS -->
    <script src="~/Sources/KayitEkran/vendor/jquery/jquery.min.js"></script>
    <script src="~/Sources/KayitEkran/js/main.js"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>