DiyetSpor/DiyetSporWeb/Controllers/DanismanDiyetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DiyetSporWeb.Models;
namespace DiyetSporWeb.Controllers
{  
    [AllowAnonymous]
    public class DanismanDiyetController : Controller
    {
        dbdiyetsporEntities db = new dbdiyetsporEntities();
        // GET: DanismanDiyet
        public ActionResult Index()
        {
           // HttpContext.User.Identity.Name; string şekilde geliyo int e çevir
            return View();
        }
        [HttpGet]
        public ActionResult Blog()
        {
            var blog = db.tblBlog.Where(x => x.blogAktiflik == true).ToList();
            ViewBag.id = Convert.ToInt32(HttpContext.User.Identity.Name);
            return View(blog);
        }
        [HttpGet]
        public ActionResult BlogYaz()
        {
            return View();
        }
        [HttpPost]
        public ActionResult BlogYaz(tblBlog b)
        {
            b.blogAktiflik = false;
            b.blogPuan = 0;
            b.kullaniciid = Convert.ToInt32(HttpContext.User.Identity.Name);
            db.tblBlog.Add(b);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult BlogAktiflik (int id)
        {
            var blog = db.tblBlog.Find(id);
            blog.blogAktiflik = false;
            db.SaveChanges();
            return RedirectToAction("Blog");
        }


        [HttpGet]
        public ActionResult Bilgilerim()
        {
            int? id = Convert.ToInt32(HttpContext.User.Identity.Name);
            var kullanici = db.tblKullanici.Find(id);
            return View(kullanici);
        }
        [HttpGet]
        public ActionResult DiyetBilgiGetir()
        {
            int? id = Convert.ToInt32(HttpContext.User.Identity.Name);
            var kullanici = db.tblKullanici.Find(id);
            return View(kullanici);
        }
        [HttpPost]
        public ActionResult DiyetBilgiGuncelle(tblKullanici k)
        {
            int? id = Convert.ToInt32(HttpContext.User.Identity.Name);
            var kullanici = db.tblKullanici.Find(id);
            kullanici.kullaniciAd = k.kullaniciAd;
            kullanici.kullaniciSoyad = k.kullaniciSoyad;
            kullanici.kullaniciTelefon = k.kullaniciTelefon;
            kullanici.kullaniciEmail = k.kullaniciEmail;
            kullanici.kullaniciSifre = k.kullaniciSifre;
            db.SaveChanges();
            return RedirectToAction("Bilgilerim");
        }



        [HttpGet]
        public ActionResult DiyetUyeGoruntule( )
        {
            List<danismanUyeGoruntulemeModel> uyeler = new List<danismanUyeGoruntulemeModel>();
            int danismanid = Convert.ToInt32(HttpContext.User.Identity.Name);
            var diyetler = db.tblDiyet.Where(x => x.diyetistenid == danismanid).ToList();
            foreach (var x in diyetler)
            {
                tblKullanici k = new tblKullanici();
                danismanUyeGoruntulemeModel testk = new danismanUyeGoruntulemeModel();
                k = db.tblKullanici.Find(x.kullaniciid);
                testk.basvuruTarihi =Convert.ToDateTime( x.diyetBaslamTarihi);
                testk.kullaniciAd = k.kullaniciAd;
                testk.kullaniciSoyad = k.kullaniciSoyad;
                testk.kullaniciEmail = k.kullaniciEmail;
                uyeler.Add(testk);
            }
               return View(uyeler);
        }
        [HttpGet]
         public ActionResult DiyetUyeTalepListele()
         {
            int? id = Convert.ToInt32(HttpContext.User.Identity.Name);
            var diyettalep = db.tblTalep.Where(x => x.talepEdilenDanisman == id ).ToList();
            List<admintalepmodel> modelliste = new List<admintalepmodel>();
            foreach (var x in diyettalep)
            {
                admintalepmodel a = new admintalepmodel();
                a.talepEdenAd = db.tblKullanici.Find(x.talepEden).kullaniciAd + " " + db.tblKullanici.Find(x.talepEden).kullaniciSoyad;
                a.talepEden = x.talepEden;
                a.talepTarihi = Convert.ToDateTime(x.talepTarihi);                
                a.talepid = x.talepid;
                a.talepEdilenDanismanAd = db.tblKullanici.Find(x.talepEden).kullaniciAd + " " + db.tblKullanici.Find(x.talepEden).kullaniciSoyad;
                a.talepEdilenDanisman = x.talepEdilenDanisman;
                a.talepTip = x.talepTip;
                
                if (x.talepDurum == true)
                    a.talepDurum = true;
                else
                    a.talepDurum = false;

                modelliste.Add(a);
            }
            return View(modelliste);
         }
        [HttpGet]
        public ActionResult TalepAktifEt(int? id)
        {
            tblTalep talep = db.tblTalep.Find(id);
            talep.talepDurum = true;
            db.SaveChanges();
            return RedirectToAction("DiyetUyeTalepListele/"+ talep.talepEdilenDanisman);
        }

        public ActionResult DenemeMinikKartlar()
        {
            return View();
        }
        public ActionResult DenemeGrafikler()
        {
            return View();
        }
        public ActionResult DenemeButonGeriKalanlar()
        {
            return View();
        }
    }
}

DiyetSpor/DiyetSporWeb/Views/DanismanDiyet/Bilgilerim.cshtml
@using DiyetSporWeb.Models
@model tblKullanici
@{
    ViewBag.Title = "Bilgilerim";
    Layout = "~/Views/Shared/_DanismanDiyetLayout.cshtml";
}

<h2>Bilgilerim</h2>


<div class="container">

    <form>
        <table border="0">
            <tr>
                <td>
                    <label>Kullanici id: </label>
                </td>
                <td>
                    @Model.kullaniciid

                </td>
            </tr>
            <tr>
                <td>
                    <label>Ad ve soyad : </label>
                </td>
                <td>
                    @Model.kullaniciAd @Model.kullaniciSoyad
                </td>
            </tr>
            <tr>
                <td>
                    <label>TC numarası: </label>
                </td>
                <td>
                    @Model.kullaniciTc
                </td>
            </tr>
            <tr>
                <td>
                    <label>Email: </label>
                </td>
                <td>
                    @Model.kullaniciEmail
                </td>
            </tr>

            <tr>
                <td>
                    <label>Doğum tarihi : </label>
                </td>
                <td>
                    @Model.kullaniciDogumTarihi
                </td>
            </tr>
            <tr>
                <td>
                    <label>Kayıt Tarihi : </label>
                </td>
                <td>
                    @Model.kullaniciKayitTarihi
                </td>
            </tr>
            <tr>
                <td>
                    <label>Telefon numarası : </label>
                </td>
                <td>
                    @Model.kullaniciTelefon
                </td>
            </tr>
            <tr>
                <td>
                    <label>Şifreniz : </label>
                </td>
                <td>
                    @Model.kullaniciSifre
                </td>
            </tr>
        </table>
    </form>
    <a href="/DanismanDiyet/DiyetBilgiGetir" class="btn btn-success">Güncelle</a>

</div>

DiyetSpor/DiyetSporWeb/Views/DanismanDiyet/Blog.cshtml
@using DiyetSporWeb.Models
@model List<tblBlog>

@{
    ViewBag.Title = "Blog";
    Layout = "~/Views/Shared/_DanismanDiyetLayout.cshtml";
}

<h2>  <a class=" btn btn-success" href="/DanismanDiyet/BlogYaz">Blog Yaz</a></h2>

@foreach (var blog in Model)
{
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">@blog.blogBaslik  |       Blog  Puan:   @blog.blogPuan </h6>
        </div>
        <div class="card-body">
            @blog.blogDetay
        </div>
        @if (blog.kullaniciid == ViewBag.id)
        {
            <div>
                <a href="/DanismanDiyet/BlogAktiflik/@blog.blogid" class="btn btn-success">Sil</a>
            </div>
        }
    </div>
    <hr />
}

DiyetSpor/DiyetSporWeb/Views/DanismanDiyet/BlogYaz.cshtml
@using DiyetSporWeb.Models
@model tblBlog
@{
    ViewBag.Title = "BlogYaz";
    Layout = "~/Views/Shared/_DanismanDiyetLayout.cshtml";
}



@using (Html.BeginForm("BlogYaz", "DanismanDiyet", FormMethod.Post))
{
<div class="form-group">

    <div>
        <lable>Başlık</lable>
        @Html.TextBoxFor(m => m.blogBaslik, new { @class = "form-control", required = "", maxlength = "50" })
    </div>

    <div>
        <lable>İçerik</lable>
        @Html.TextBoxFor(m => m.blogDetay, new { @class = "form-control", required = "", maxlength = "500" })
    </div>

</div>
    <button type="submit" class="form-control success">Yaz</button>
}

DiyetSpor/DiyetSporWeb/Views/DanismanDiyet/DenemeButonGeriKalanlar.cshtml
@{
    ViewBag.Title = "DenemeButonGeriKalanlar";
    Layout = "~/Views/Shared/_DanismanDiyetLayout.cshtml";
}

<h2>DenemeButonGeriKalanlar</h2>



<!-- Content Row --> <!--4 lü kısım-->
<div class="row">

    <!-- Content Column -->
    <div class="col-lg-6 mb-4">

        <!-- Project Card Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Projects</h6>
            </div>
            <div class="card-body">
                <h4 class="small font-weight-bold">Server Migration <span class="float-right">20%</span></h4>
                <div class="progress mb-4">
                    <div class="progress-bar bg-danger" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <h4 class="small font-weight-bold">Sales Tracking <span class="float-right">40%</span></h4>
                <div class="progress mb-4">
                    <div class="progress-bar bg-warning" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <h4 class="small font-weight-bold">Customer Database <span class="float-right">60%</span></h4>
                <div class="progress mb-4">
                    <div class="progress-bar" role="progressbar" style="width: 60%" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <h4 class="small font-weight-bold">Payout Details <span class="float-right">80%</span></h4>
                <div class="progress mb-4">
                    <div class="progress-bar bg-info" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
                <h4 class="small font-weight-bold">Account Setup <span class="float-right">Complete!</span></h4>
                <div class="progress">
                    <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            </div>
        </div>

        <!-- Color System -->
        <div class="row">
            <div class="col-lg-6 mb-4">
                <div class="card bg-primary text-white shadow">
                    <div class="card-body">
                        Primary
                        <div class="text-white-50 small">#4e73df</div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mb-4">
                <div class="card bg-success text-white shadow">
                    <div class="card-body">
                        Success
                        <div class="text-white-50 small">#1cc88a</div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mb-4">
                <div class="card bg-info text-white shadow">
                    <div class="card-body">
                        Info
                        <div class="text-white-50 small">#36b9cc</div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mb-4">
                <div class="card bg-warning text-white shadow">
                    <div class="card-body">
                        Warning
                        <div class="text-white-50 small">#f6c23e</div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mb-4">
                <div class="card bg-danger text-white shadow">
                    <div class="card-body">
                        Danger
                        <div class="text-white-50 small">#e74a3b</div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 mb-4">
                <div class="card bg-secondary text-white shadow">
                    <div class="card-body">
                        Secondary
                        <div class="text-white-50 small">#858796</div>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <div class="col-lg-6 mb-4">

        <!-- Illustrations -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Illustrations</h6>
            </div>
            <div class="card-body">
                <div class="text-center">
                    <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;" src="/Sources/AdminAnasayfa/img/undraw_posting_photo.svg" alt="">
                </div>
                <p>Add some quality, svg illustrations to your project courtesy of <a target="_blank" rel="nofollow" href="https://undraw.co/">unDraw</a>, a constantly updated collection of beautiful svg images that you can use completely free and without attribution!</p>
                <a target="_blank" rel="nofollow" href="https://undraw.co/">Browse Illustrations on unDraw &rarr;</a>
            </div>
        </div>

        <!-- Approach -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Development Approach</h6>
            </div>
            <div class="card-body">
                <p>SB Admin 2 makes extensive use of Bootstrap 4 utility classes in order to reduce CSS bloat and poor page performance. Custom CSS classes are used to create custom components and custom utility classes.</p>
                <p class="mb-0">Before working with this theme, you should become familiar with the Bootstrap framework, especially the utility classes.</p>
            </div>
        </div>

    </div>
</div>

DiyetSpor/DiyetSporWeb/Views/DanismanDiyet/DenemeGrafikler.cshtml
@{
    ViewBag.Title = "DenemeGrafikler";
    Layout = "~/Views/Shared/_DanismanDiyetLayout.cshtml";
}

<h2>DenemeGrafikler</h2>


<!-- Content Row --> <!-- grafik ve yuvarlak grafik -->

<div class="row">

    <!-- Area Chart -->
    <div class="col-xl-8 col-lg-7">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Earnings Overview</h6>
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">Dropdown Header:</div>
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="chart-area">
                    <canvas id="myAreaChart"></canvas>
                </div>
            </div>
        </div>
    </div>

    <!-- Pie Chart -->
    <div class="col-xl-4 col-lg-5">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown --> <!--Grafiği üzeründeki 3 noktalı menu-->
            <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                <h6 class="m-0 font-weight-bold text-primary">Revenue Sources</h6>
                <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">Dropdown Header:</div>
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </div>
            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="chart-pie pt-4 pb-2">
                    <canvas id="myPieChart"></canvas>
                </div>
                <div class="mt-4 text-center small">
                    <span class="mr-2">
                        <i class="fas fa-circle text-primary"></i> Direct
                    </span>
                    <span class="mr-2">
                        <i class="fas fa-circle text-success"></i> Social
                    </span>
                    <span class="mr-2">
                        <i class="fas fa-circle text-info"></i> Referral
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>

DiyetSpor/DiyetSporWeb/Views/DanismanDiyet/DenemeMinikKartlar.cshtml
@{
    ViewBag.Title = "DenemeMinikKartlar";
    Layout = "~/Views/Shared/_DanismanDiyetLayout.cshtml";
}

<h2>DenemeMinikKartlar</h2>


<!-- Content Row -->  <!--4 Tane yanyana duran minik kartlar-->
<div class="row">

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Earnings (Monthly)</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">$40,000</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Earnings (Annual)</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">$215,000</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks</div>
                        <div class="row no-gutters align-items-center">
                            <div class="col-auto">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                            </div>
                            <div class="col">
                                <div class="progress progress-sm mr-2">
                                    <div class="progress-bar bg-info" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Pending Requests Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Pending Requests</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-comments fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

DiyetSpor/DiyetSporWeb/Views/DanismanDiyet/DiyetBilgiGetir.cshtml
@using DiyetSporWeb.Models
@model tblKullanici
@{
    @{
        ViewBag.Title = "DiyetBilgiGetir";
        Layout = "~/Views/Shared/_DanismanDiyetLayout.cshtml";
    }

    <h2>DiyetBilgiGetir</h2>


    @using (Html.BeginForm("DiyetBilgiGuncelle", "DanismanDiyet", FormMethod.Post))
    {
        <div class="form-group">
            <div>
                <lable>Kullanici id</lable>
                @Html.TextBoxFor(m => m.kullaniciid, new { @class = "form-control", @readonly = "readonly" })
            </div>
            <div>
                <lable>Ad</lable>
                @Html.TextBoxFor(m => m.kullaniciAd, new { @class = "form-control", required = "", maxlength = "20" })
            </div>
            <div>
                <lable>Soyad</lable>
                @Html.TextBoxFor(m => m.kullaniciSoyad, new { @class = "form-control", required = "", maxlength = "20" })
            </div>
            <div>
                <lable>Kullanici TC numarası</lable>
                @Html.TextBoxFor(m => m.kullaniciTc, new { @class = "form-control", @readonly = "readonly" })
            </div>
            <div>
                <label>Şifresi</label>
                @Html.TextBoxFor(m => m.kullaniciSifre, new { @class = "form-control", required = "", maxlength = "10" })
                @Html.ValidationMessageFor(m => m.kullaniciSifre, "", new { @style = "color:red" })
            </div>
            <div>
                <lable>Müşteri Doğum Günü</lable>
                @Html.TextBoxFor(m => m.kullaniciDogumTarihi, new { @class = "form-control", @readonly = "readonly" })
            </div>
            <div>
                <lable>Müşteri Telefon</lable>
                @Html.TextBoxFor(m => m.kullaniciTelefon, new { @class = "form-control", maxlength = "11" })
                @Html.ValidationMessageFor(m => m.kullaniciTelefon, "", new { @style = "color:red" })
            </div>
            <div>
                <lable>Müşteri Eposta</lable>
                @Html.TextBoxFor(m => m.kullaniciEmail, new { @class = "form-control", maxlength = "100" })
                @Html.ValidationMessageFor(m => m.kullaniciEmail, "", new { @style = "color:red" })
            </div>

        </div>
        <button type="submit" class="form-control success">Güncelle</button>
    }

DiyetSpor/DiyetSporWeb/Views/DanismanDiyet/DiyetUyeGoruntule.cshtml
@using DiyetSporWeb.Models
@model List<danismanUyeGoruntulemeModel>
@{
    ViewBag.Title = "DiyetUyeGoruntule";
    Layout = "~/Views/Shared/_DanismanDiyetLayout.cshtml";
}
 
<div class="container-fluid"> 
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"> Üyeler</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr> 
                            <th>Uye adı</th>
                            <th>Uye Soyadı</th>
                            <th>E mail</th>
                            <th>Uye Kayıt</th>
                            <th>Goruntüle</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr> 
                            <th>Uye adı</th>
                            <th>Uye Soyadı</th>
                            <th>E mail</th>
                            <th>Uye Kayıt</th>
                            <th>Goruntüle</th>
                        </tr>
                    </tfoot>
                    <tbody> 
                        @foreach (var uye in Model)
                        {
                            <tr> 
                                <td>@uye.kullaniciAd</td>
                                <td>@uye.kullaniciSoyad</td> 
                                <td>@uye.kullaniciEmail</td>
                                <td>@uye.basvuruTarihi</td>
                                <td>
                                    <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">GÖRÜNTÜLE</a> 
                                </td> 
                            </tr>
                        } 
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

DiyetSpor/DiyetSporWeb/Views/DanismanDiyet/DiyetUyeTalepListele.cshtml
@using DiyetSporWeb.Models
@model List<admintalepmodel>

@{
    ViewBag.Title = "DiyetUyeTalepListele";
    Layout = "~/Views/Shared/_DanismanDiyetLayout.cshtml";
}
 
<div class="container-fluid">
     
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"> Bekleyen Onaylar</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>

                            <th>Talep Eden</th>

                            <th>Talep Tarihi</th>
                            <th>Talep Tipi</th>
                            <th>Talep Durumu</th>
                            <th>Durum Değiştir</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Talep Eden</th>

                            <th>Talep Tarihi</th>
                            <th>Talep Tipi</th>
                            <th>Talep Durumu</th>
                            <th>Durum Değiştir</th>
                        </tr>
                    </tfoot>
                    <tbody>

                        @foreach (var talep in Model)
                        {
                            <tr>

                                <td>   @talep.talepEdenAd</td>

                                <td>@talep.talepTarihi</td>
                                <td>@talep.talepTip</td>

                                @if (@talep.talepDurum == false)
                                {
                                    <td>
                                        ONAY BEKLİYOR
                                    </td>
                                }
                                else
                                {
                                    <td>
                                        ONAYLANDI
                                    </td>
                                }

                                @if (talep.talepDurum == false)
                                {
                                    <td>
                                        <a href="/DanismanDiyet/TalepAktifEt/@talep.talepid" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">ONAYLA</a>

                                    </td>
                                }
                                else
                                {
                                    <td>
                                        ONAYLANMIŞ
                                    </td>
                                }


                            </tr>
                        }


                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

DiyetSpor/DiyetSporWeb/Views/DanismanDiyet/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_DanismanDiyetLayout.cshtml";
}

<h2>Index</h2>